mod feats;

pub use feats::{
    // Combate
    Alert,
    Charger,
    CrossbowExpert,
    DefensiveDuelist,
    DualWielder,
    GreatWeaponMaster,
    Grappler,
    MageSlayer,
    MountedCombatant,
    PolearmMaster,
    SavageAttacker,
    Sentinel,
    Sharpshooter,
    ShieldMaster,
    SpellSniper,
    TavernBrawler,
    WarCaster,
    WeaponMaster,
    // Habilidad y Exploración
    Actor,
    Athlete,
    DungeonDelver,
    Durable,
    HeavilyArmored,
    HeavyArmorMaster,
    InspiringLeader,
    KeenMind,
    LightlyArmored,
    Lucky,
    MartialAdept,
    MediumArmorMaster,
    Mobile,
    ModeratelyArmored,
    Observant,
    Resilient,
    Skilled,
    Skulker,
    Tough,
    // Mágicos
    ElementalAdept,
    Healer,
    MagicInitiate,
    RitualCaster,
};
